name = "storganizer"
main = "src/index.ts"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "storganizer-db"
database_id = "0a8594a9-3d3d-4939-bb35-fe7ba447806c"
migrations_dir = "src/db/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "storganizer-storage"

[[queues.producers]]
queue = "storganizer-image-queue"
binding = "IMAGE_QUEUE"

[[queues.consumers]]
queue = "storganizer-image-queue"
max_batch_size = 10
max_batch_timeout = 30

[assets]
directory = "../web/dist"
binding = "ASSETS"

[vars]
GOOGLE_CLIENT_ID = "494613233168-ksrso4biqbtoaet59skiebgpahoro29s.apps.googleusercontent.com"
